config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :transactions
  resources :users
end

app/models/address.rb
class Address < ApplicationRecord

  validates :street, :city, :state, :neighbourhood, :postal_code, presence: true
  has_many :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord

  belongs_to :user

  validates :amount, :quotation, :currency, :transaction_type, :user_id, presence: true
  
  def currency_pt
    currency == 'dollar' ? 'Dólar' : 'Real'
  end

  def transaction_type_pt
    transaction_type == 'buy' ? 'Compra' : 'Venda'
  end

  def total
    value = amount
    value /= quotation if currency == 'real'
    value *= -1 if transaction_type == 'sell'
    "$  #{'%.2f' % value}"
  end

  def date
    created_at.strftime('%d/%m/%Y')
  end

  def total_num
    value = amount
    value /= quotation if currency == 'real'
    value *= -1 if transaction_type == 'sell'
    value
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :transactions
  belongs_to :address, optional: true
  validates :name, :email, :cpf, presence: true
end

app/controllers/addresses_controller.rb
class AddressesController < ActionController::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    case params[:filter]
    when nil
      @transactions = Transaction.where(created_at: Date.today.all_day)
    when 'all'
      @transactions = Transaction.all
    else
      @transactions = Transaction.where(currency: params[:filter])
    end

    @total = 0.0
    @transactions.each do |t|
      @total += t.total_num
    end
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def show
    @transaction = Transaction.find(params[:id])
    @user = User.find(@transaction.user_id)
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = Transaction.new(transaction_params)

    if @transaction.save
      redirect_to @transaction
    else
      render :new
    end
  end

  def edit
    @transaction = Transaction.find(params[:id])
  end

  def update
    @transaction = Transaction.find(params[:id])

    if @transaction.update(transaction_params)
      redirect_to @transaction
    else
      render :edit
    end
  end

  def destroy
    @transaction = Transaction.find(params[:id])
    @transaction.destroy
    redirect_to root_path, notice: 'Transação apagada com sucesso!'
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount,
      :currency, :quotation, :transaction_type, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def edit
    @user = User.new
  end

  def update
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
  end

  private

  def user_params
    params.require(:user).permit(:email, :cpf, :name, :address_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Bem-vindo ao sistema de trocas de moedas</h1>

<%= link_to 'Registrar transação', new_transaction_path %>
<%= link_to 'Cadastrar usuário', new_user_path %>
<%= link_to 'Usuários', users_path %>

<%= form_tag '', method: :get do %>
    <%= label_tag :filter, 'Filtro por moeda' %>
    <%= select_tag :filter, options_for_select( [['Dólar', 'dollar'], ['Real', 'real']]) %>
    <%= submit_tag 'Filtrar' %>
<% end %>

<%= link_to 'Ver todas', root_path(filter: 'all') %>

<% if @transactions.empty? %>
    <h2>Você ainda não possui transações cadastradas.</h2>
<% else %>
    <table>
        <thead>
            <tr>
                <th>Identificador</th>
                <th>Quantidade</th>
                <th>Moeda</th>
                <th>Tipo</th>
                <th>Total</th>
            </tr>
        </thead>
        <tbody>
            <% @transactions.each do |t| %>
            <tr>
                <td><%= link_to t.id, t %></td>
                <td><%= t.amount %></td>
                <td><%= t.currency_pt %></td>
                <td><%= t.transaction_type_pt %></td>
                <td><%= t.total %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
    <h4>Total agregado: $ <%= "%.2f" % @total %></h4>
<% end %>
<%= notice %>  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CasaDeCambio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/transactions/edit.html.erb
<% unless @transaction.errors.blank? %>
<h3>Você deve informar todos os dados da transação</h3>
<% end %>

<%= form_for @transaction do |t| %>
  <%= t.label :amount, 'Quantidade' %>
  <%= t.text_field :amount %>
  <%= t.label :currency, 'Moeda' %>
  <%= t.select :currency, [['Dólar', 'dollar'], ['Real', 'real']] %>
  <%= t.label :quotation, 'Cotação' %>
  <%= t.text_field :quotation %>
  <%= t.label :transaction_type, 'Tipo' %>
  <%= t.select :transaction_type, [['Compra', 'buy'], ['Venda', 'sell']] %>

  <%= t.submit 'Editar' %>
<% end %>

app/views/transactions/new.html.erb
<% unless @transaction.errors.blank? %>
<h3>Você deve informar todos os dados da transação</h3>
<% end %>

<%= form_for @transaction do |t| %>
  <%= t.label :amount, 'Quantidade' %>
  <%= t.text_field :amount %>
  <%= t.label :currency, 'Moeda' %>
  <%= t.select :currency, [['Dólar', 'dollar'], ['Real', 'real']] %>
  <%= t.label :quotation, 'Cotação' %>
  <%= t.text_field :quotation %>
  <%= t.label :transaction_type, 'Tipo' %>
  <%= t.select :transaction_type, [['Compra', 'buy'], ['Venda', 'sell']] %>
  <%= t.label :user_id, 'Usuário' %>
  <%= t.collection_select :user_id, User.all, :id, :email %>

  <%= t.submit 'Cadastrar'%>
<% end %>

app/views/transactions/show.html.erb
<h3>Identificador</h3>
<p><%= @transaction.id %></p>
<h3>Usuário</h3>
<p><%= @user.email %></p>
<h3>Quantidade</h3>
<p><%= @transaction.amount %></p>
<h3>Moeda</h3>
<p><%= @transaction.currency_pt %></p>
<h3>Cotação</h3>
<p><%= '$ %.2f' % @transaction.quotation %></p>
<h3>Tipo</h3>
<p><%= @transaction.transaction_type_pt %></p>
<h3>Data</h3>
<p><%= @transaction.date %></p>
<h3>Total</h3>
<p><%= @transaction.total %></p>

<%= link_to 'Editar', edit_transaction_path(@transaction) %>
<%= link_to 'Apagar', @transaction, method: :delete %>
<%= link_to 'Voltar', root_path %>

app/views/users/edit.html.erb
<% unless @user.errors.blank? %>
<h3>Você deve informar todos os dados do usuário</h3>
<% end %>

<%= form_for @user do |t| %>
  <%= t.label :name, 'Nome' %>
  <%= t.text_field :name %>
  <%= t.label :email, 'E-mail' %>
  <%= t.text_field :email %>
  <%= t.label :cpf, 'CPF' %>
  <%= t.text_field :cpf %>

  <%= t.submit 'Editar' %>
<% end %>

app/views/users/index.html.erb
<% unless @users.empty? %>
    <table>
        <thead>
            <tr>
                <th>Identificador</th>
                <th>E-mail</th>
            </tr>
        </thead>
        <tbody>
            <% @users.each do |u| %>
            <tr>
                <td><%= link_to u.id, u %></td>
                <td><%= u.email %></td>
            </tr>
            <% end %>
        </tbody>
    </table>
<% else %>
    <p>Nenhum usuário cadastrado</p>
<% end %>

app/views/users/new.html.erb
<% unless @user.errors.blank? %>
<h3>Você deve informar todos os dados do usuário</h3>
<% end %>

<%= form_for @user do |t| %>
  <%= t.label :name, 'Nome' %>
  <%= t.text_field :name %>
  <%= t.label :email, 'E-mail' %>
  <%= t.text_field :email %>
  <%= t.label :cpf, 'CPF' %>
  <%= t.text_field :cpf %>

  <%= t.submit 'Cadastrar'%>
<% end %>

app/views/users/show.html.erb
<h3><%= @user.name %></h3>
<h3>E-mail:</h3>
<p><%= @user.email %></p>
<h3>CPF: </h3>
<p><%= @user.cpf %></p>

<h3>Endereço:</h3>
<% if @user.address %>
    <p><%= @user.address.street %></p>
    <p><%= @user.address.neighbourhood %></p>
    <p><%= @user.address.city %> - <%= @user.address.state %></p>
    <p><%= @user.address.postal_code %></p>
<% else %>
    <p> Este usuário não tem um endereço cadastrado </p>
<% end %>
<%= link_to 'Editar', edit_user_path(@user) %>